name:                linear-prefs
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/many-matching#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - MonadRandom
  - diagrams
  - diagrams-lib
  - diagrams-svg
  - pretty-simple
  - containers
    # - glpk-hs
  - hmatrix-glpk
  - hmatrix
    # - typed-spreadsheet
  - diagrams-canvas
  - deepseq

executables:
  many-matching:
    source-dirs:      src
    main:             Main.hs
    ghc-options: -Wwarn -Wall -Wno-deprecations
